Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -76,32 +76,32 @@ jobs:
       run: |
         echo "Event name: ${{ github.event_name }}"
     
-    # Add a comment to pull requests with plan results
-    - name: add-plan-comment
-      id: comment_before_deployment
-      uses: actions/github-script@v3
-      if: github.event_name == 'pull_request' && (success() || failure())
-      env:
-        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-      with:
-        github-token: ${{ secrets.GH_TOKEN }}
-        script: |
-          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-          #### Terraform Validation 🤖${{ steps.validate.outputs.stdout }}
-          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-          #### Checkov 🧪\`${{ steps.checkov.outcome }}\`
-          #test with token
-          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
+#     # Add a comment to pull requests with plan results
+#     - name: add-plan-comment
+#       id: comment_before_deployment
+#       uses: actions/github-script@v3
+#       if: github.event_name == 'pull_request' && (success() || failure())
+#       env:
+#         PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+#       with:
+#         github-token: ${{ secrets.GH_TOKEN }}
+#         script: |
+#           const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+#           #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+#           #### Terraform Validation 🤖${{ steps.validate.outputs.stdout }}
+#           #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+#           #### Checkov 🧪\`${{ steps.checkov.outcome }}\`
+#           #test with token
+#           *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
             
-          github.issues.createComment({
-            issue_number: context.issue.number,
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            body: output
-          })
+#           github.issues.createComment({
+#             issue_number: context.issue.number,
+#             owner: context.repo.owner,
+#             repo: context.repo.repo,
+#             body: output
+#           })
 
-      # On push to main, build or change infrastructure according to Terraform configuration files
+#       # On push to main, build or change infrastructure according to Terraform configuration files
     - name: Terraform Apply
       if: github.event_name == 'pull_request' || github.ref == 'refs/heads/"main"' && github.event_name == 'push'
       env:
